### ISSUE TITLE
Color Picker Palette Popup

### ISSUE THREAD

**Issue by Djspaceg** [enactjs/agate#67]
We need a color picker popup UI for the color picker component when the system is unable to provide a UI. This will likely replace the built-in OS popup that appears on macOS.

## Requirements:
* The popup should appear when a user activates a color picker and remain open until they close it, or is dismissed by clicking somewhere else
* The selection method should allow the full range of colors from everything between #000000 and #ffffff
* The output should be in the hex (web-safe) color format (ex: `#rrggbb`)
* The interface should:
   * visually represent at least HSL (hue, saturation, lightness), and possibly other methods.
   * work with both touch and pointer.
   * use "math" to calculate the value, rather than reading rasterized pixels from a canvas element.
   * be dynamically scalable (use linear gradients) and possibly filters as blend-modes
* The input value should be "pre-selected" (represented in the UI) when popup opens.
* Color swatches (preset colors) definable in an array of hex strings as a prop on the picker popup component. Clicking/activating one should immediately update the popup's color selection, and not dismiss the popup (allowing the user to tune that color, not the preset, just the output)
* Use the module `color-convert` for color conversion. It's already part of Agate

## Nice to have
* 2 different styles of color seleciton, i.e. a 2D vertical/horizontal color space representation plus a lightness slider; and a set of 3 sliders for hue, saturation, and lightness
* at least two color picking mechanisms: HSL, HSV, direct HEX input, etc

Here's a link to some HSL color theory:
https://en.wikipedia.org/wiki/HSL_and_HSV

_**Example of a 2D picker with one slider:**_
<img width="245" alt="screen shot 2018-10-22 at 4 54 38 pm" src="https://user-images.githubusercontent.com/386529/47325949-57c83600-d61b-11e8-8039-a30c4c6a45c2.png">

_**Example of a 3-slider picker:**_
<img width="248" alt="screen shot 2018-10-19 at 1 37 28 pm" src="https://user-images.githubusercontent.com/386529/47325941-526aeb80-d61b-11e8-9b84-92ad4dc8afc6.png">

_**Note:** The color on the both of the example's secondary sliders change based on the currently selected hue._

**Comment by teckliew** [comment]
Since we are simplifying this color picker to having limited number of color swatches, I'm thinking about making the color picker expandable instead of a popup.
The expandable color picker includes a swatch drawer that slides out and overlays the color picker's neighbors (to avoid layout repaint).
Configurable options: the colors of the swatches, direction in which the drawer slides out, the background of the drawer, and possibly the format (hex, hsla, or rgba). Ideally, any number of swatches should be supported, but that introduces more complexity where we might need to use scroller or pagination or Moonstone-style picker.

![expandablecolorpickerdemo](https://user-images.githubusercontent.com/8940009/47820093-b70fff80-dd19-11e8-958c-f469657b7f94.gif)
